---

- hosts: all
  become: true
  tasks:

  - name: update cache, then install apache2 and php packages (Debian)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update cache, then install httpd and php packages (RedHat)
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["RedHat", "CentOS"]
