---

- hosts: all
  become: true
  tasks:

  - name: update cache, then install apache and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
