---

- hosts: all
  become: true
  tasks:

  - name: update repository index (Debian)
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]

  - name: install apache2 and php packages (Debian)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index (RedHat)
    dnf:
      update_cache: yes
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: install httpd and php packages (RedHat)
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RedHat", "CentOS"]
