---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages (Debian)
    tags: apache,apache2,debian,ubuntu,linuxmint
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]

  - name: install httpd and php packages (RedHat)
    tags: apache,httpd,redhat,centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RedHat", "CentOS"]


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: mariadb,redhat,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: install mariadb package (Debian)
    tags: mariadb,debian,ubuntu,linuxmint
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


- hosts: vbox_hosts
  become: true
  tasks:

  - name: install bpytop, tmux packages
    package:
      name:
        - bpytop
        - tmux
      state: latest


- hosts: workstations
  become: true
  tasks:

  - name: install packages  (workstations)
    package:
      name:
        - bpytop
        - tmux
        - bat
        - spell
        - colordiff
        - ncdu
      state: latest
