---
#
# site.yml
# Update all servers in inventory file
#
# usage:  ansible-playbook site.yml
#

# update repository cache
- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (RedHat)
    tags: always
    dnf:
      update_cache: yes
      autoremove: true
    changed_when: false
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: update repo cache (Debian)
    tags: always
    apt:
      update_cache: yes
      autoremove: true
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint", "Pop!_OS"]


# add ssh key
- hosts: all
  become: true
  roles:
    - base

# workstations
- hosts: workstations
  become: true
  roles:
    - workstations

# web_servers
- hosts: web_servers
  become: true
  roles:
    - web_servers

# nginx_servers
- hosts: nginx_servers
  become: true
  roles:
    - nginx_servers

# db_servers
- hosts: db_servers
  become: true
  roles:
    - db_servers

# file_servers
- hosts: file_servers
  become: true
  roles:
    - file_servers
